-- MySQL Script generated by MySQL Workbench
-- Sun Oct 27 21:37:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cuponera
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cuponera` ;

-- -----------------------------------------------------
-- Schema cuponera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuponera` ;
USE `cuponera` ;

-- -----------------------------------------------------
-- Table `cuponera`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuponera`.`subcategoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuponera`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuponera`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `tipousuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `estado` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuponera`.`cuponventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuponera`.`cuponventa` (
  `idcuponventa` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` FLOAT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcuponventa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuponera`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuponera`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `codgio` VARCHAR(8) NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `imagen` VARCHAR(60) NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idproductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuponera`.`productos_has_cuponventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuponera`.`productos_has_cuponventa` (
  `productos_idproductos` INT NOT NULL,
  `cuponventa_idcuponventa` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
